
spring:
  datasource:
    url: jdbc:h2:mem:employeedb-dev
    driver-class-name: org.h2.Driver
    username: dev
    password: "dev"

logging:
  level:
    root: INFO
    io.upskilling.training.employee: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE